// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var http;

  http = require('http');

  module.exports = Controller('Home/BaseController', function() {
    return {
      songAction: function(source) {
        var buffers, req, that;
        that = this;
        source = decodeURIComponent(source);
        buffers = [];
        req = http.request({
          hostname: 'file.qianqian.com',
          port: 80,
          path: source.replace('http://file.qianqian.com/', ''),
          method: 'GET',
          headers: {
            'Accept-Encoding': 'identity;q=1, *;q=0',
            'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
            'Host': 'file.qianqian.com',
            'Pragma': 'no-cache',
            'Range': 'bytes=0-',
            'Referer': 'http://file.qianqian.com/',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36'
          }
        }, function(res) {
          res.on('data', function(chuck) {
            return buffers.push(chuck);
          });
          return res.on('end', function() {
            that.http.cthIsSend = true;
            that.http.setHeader('Content-Type', 'audio/mpeg');
            buffers = Buffer.concat(buffers);
            return that.end(buffers);
          });
        });
        return req.end();
      }
    };
  });

}).call(this);

//# sourceMappingURL=MusicController.js.map
